parameters:
#    matuck_library.example.class: matuck\LibraryBundle\Example

services:
    matuck_library.iphash:
        scope: request
        class: matuck\LibraryBundle\Lib\IpHash
        arguments: ["@request"]
    matuck_library.nameparser:
        class: matuck\LibraryBundle\Lib\nameparser
    matuck_library.filehandler:
        class: matuck\LibraryBundle\Lib\Filehandler\Filehandler
        arguments:  [ "@service_container" ]
    matuck_library.googlebookapi:
        class: matuck\LibraryBundle\Lib\GoogleBookApi
        arguments:  [ "@service_container" ]
    matuck.twig.matuck_extension:
        class: matuck\LibraryBundle\Twig\matuckExtension
        arguments: 
            fh: "@matuck_library.filehandler"
            fpntag: "@fpn_tag.tag_manager"
            nsfwtags: %matuck_library_nsfwtags%
        tags:
            - { name: twig.extension }
    matuck_library.searchindexer:
        class: matuck\LibraryBundle\Lib\Indexer
        arguments:
             index: "@ivory_lucene_search"
             fpntag: "@fpn_tag.tag_manager"
#    matuck_library.example:
#        class: %matuck_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    